
; this is ancient enough... pour moi, cherie.
(define releases '("13.0" "12.2" "12.1" "12.0" "11.0" "10.2" "10.1" "10.0" "9.1" "9.0" "8.1" "8.0" "7.1" "7.0" "4.0"))
; above should be ordered or how will the below know?
(define range '("13.0" . "8.1"))

; this project is actually getting too big for my own grasp and it's sooo small
(define (start)
  (load-config)
  (init-mirrors)
  (__bootstrap))

(define (in-range? ns)
  (member ns
	  (let ((start (car range))
		(end (cdr range)))
	    (let find ((r releases))
	      (if (null? r)
		  '()
		  (if (equal? start (car r))
		      (cons (car r)
			    (let found ((y (cdr r)))
			      (if (null? y)
				  '()
				  (if (equal? end (car y))
				      (cons end '())
				      (cons (car y)
					    (found (cdr y)))))))
		      (find (cdr r))))))))

(define (move-to num-str)
  (if (in-range? num-str)
      (begin (switch-release num-str)
	     (init-mirrors)
	     (__bootstrap))
      (begin (display "Not in range ")
	     (display (in-range? (car range)))
	     (newline)
	     (status)
;	     (display "; staying with: ")
;	     (display (version))
;	     (display ".") (newline)
	     #f)))

(define (status)
  (display "local(")
  (display (local-version)) (display ") ")
  (display "remote(")
  (display (version)) (display ")")
  (newline)
  (list-mirrors)
  (display "Using ")
  (display (mirror-string))
  (let ((trap (mirror-strings)))
    (if (and trap (not (null? trap)))
	(for-each (lambda (ms)
		  (display " ")
		  (display ms))
		(mirror-strings))))
  (newline)
  (pkg-stats))
