(define (smsw-load)
  (config)
  (let ((root "@SMSW_LIB@"))
    (load (string-append root "/scheme/packages.scm"))))
(smsw-load)
(define (smsw-refresh)
  (smsw-load)
  (reload-package 'smsw))
;(user-package-is 'snfpmi)
;(in 'snfpmi)
;(exec)
;(user `(in snfpmi (dothis)))
(display ",in smsw")
(newline)
